# Generated by Django 5.0.6 on 2024-06-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='trabajadores',
        ),
        migrations.AlterModelTable(
            name='proyectotrabajadores',
            table='proyecto_trabajadores',
        ),
        migrations.DeleteModel(
            name='AsignacionProyecto',
        ),
    ]
