# Generated by Django 5.0.6 on 2024-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='faena',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_faena',
            field=models.CharField(default='faena1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(default='proyecto1', max_length=200),
            preserve_default=False,
        ),
    ]
