# Generated by Django 5.0.6 on 2024-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.CharField(max_length=100),
        ),
    ]
