# Generated by Django 5.0.6 on 2024-05-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_alter_cargo_nombre_alter_trabajador_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
